### ISSUE TITLE
Publisher - no indicator to illustrate that some fields are required

### ISSUE THREAD

**Issue by Rob-pw** [dloa/browser-react#51]
No indicator to illustrate that some fields are required, prior to clicking 'preview'.

![peek 2017-04-28 03-14](https://cloud.githubusercontent.com/assets/4596295/25511763/d3820b88-2bc0-11e7-8fda-6eb296449ab5.gif)

**Comment by OstlerDev** [comment]
There should be indicators that change the styling, but I wouldn't be surprised if they were broken in the merge to the dashboard. We should also add indicators to required fields before submission. However since this is dealing with the publisher, it would be best to post the issue to https://github.com/dloa/web-publisher/ (the github repo that contains the publisher)

**Comment by Rob-pw** [comment]
dloa/web-publisher must be private, I'm unable to see it.

**Comment by OstlerDev** [comment]
Apologies, its actually https://github.com/dloa/publisher-web :)

**Comment by Rob-pw** [comment]
Aha, that'd explain it :3 I'll check and copy the publisher issues over - likely tomorrow
